//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelRezervationMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblHakkimda
    {
        public int ID { get; set; }
        public string Hakkimda1 { get; set; }
        public string Hakkimda2 { get; set; }
        public string Hakkimda3 { get; set; }
        public string Hakkimda4 { get; set; }
    }
}
