//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelRezervationMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbliletisim
    {
        public int ID { get; set; }
        public string Aciklama { get; set; }
        public string Koordinat { get; set; }
        public string Telefon { get; set; }
        public string Mail { get; set; }
        public string Adres { get; set; }
    }
}
